version: '3'
services:
  mongo:
    container_name: crypto_mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: lgPlCQDFlA
      MONGO_INITDB_DATABASE: crypto
    volumes:
      - ./volumes/mongo-data:/data/db
    command: mongod --port 27019
    ports:
      - "0.0.0.0:27019:27019"
  front:
    container_name: crypto_front
    build: ./
    restart: always
    env_file: ./.env
    ports:
        - "127.0.0.1:4300:4300"
    links:
        - mongo
    labels:
        - traefik.enable=true
        - "traefik.http.routers.3tour-front.rule=Host(`www.3tour.ir,3tour.ir`)"
  crypto_mongoexpress:
    image: mongo-express
    container_name: crypto-mongoexpress
    ports:
        - "8023:8081"
    links:
        - mongo
    environment:
        ME_CONFIG_MONGODB_SERVER: mongo
        ME_CONFIG_MONGODB_PORT: 27019
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: lgPlCQDFlA
        ME_CONFIG_BASICAUTH_USERNAME: admin
        ME_CONFIG_BASICAUTH_PASSWORD: Hamidmoradi_21
